### PR TITLE
Update of dependencies and introduction of metric namespace

### PR DESCRIPTION
**Pull request by elonmir**
Pushed the dependencies to mitigate CVEs.

### CODE REVIEW

**Comment by elonmir** [comment]
I also added a feature to make the namespace of the metrics configureable.

For details take a look in both of my local prs:
* https://github.com/elonmir/filestat_exporter/pull/2
* https://github.com/elonmir/filestat_exporter/pull/1

**Comment by michael-doubez** [comment]
Hello,

What do you call namespace ?

**Comment by elonmir** [comment]
Per default, every metric is written into `file_state_XXX`. In the original code, that was put in the variablee `namespace`, hence I made that part configureable. So if you want to group metrics by namespaces, so to speak, you would be able to do that.

**Comment by michael-doubez** [comment]
Added additional optional label `tree` in #42.
This allows an additional dimension to file stats metrics and, as an added feature, opens the possibility to work on different root path.

Changing the namespace is actually changes the metric name and it is very hard to work with in prometheus.
The job label is rather used when wanting to scope metric collections. If a metric name change is desirable, you can always relabel them at ingestion time.

I'll close the PR.

**Pull request closed without merging**
